#!/bin/bash

# clone standard
git clone --depth 1 http://github.com/feross/standard

# copy to parent
rsync -av --exclude={LICENSE,README.md,test.js,.git,package.json} standard/ ../

sed -i.original 's/"semi": \[2, "never"\]/"semi": \[2, "always"\]/' ../rc/.eslintrc

node mergejson.js > ../mergedpackage.json

mv ../mergedpackage.json ../package.json

rm -rf standard
